---
- name: DNSを近いところに差し替え
  replace:
    path: /etc/systemd/resolved.conf
    regexp: "^DNS=.*$"
    replace: "DNS=10.0.0.1 10.16.0.2"
- name: リゾルバの再起動
  systemd:
    name: systemd-resolved.service
    state: restarted
